# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c09b60f7f899a00f29cb1d61b34d68b31d00e24e711f512a9871eaa8b94da66f16f38e01689f06ed83c40c975f3324b46e06a0fceea2f51af243e982f39b844e

test:
  secret_key_base: fba9a5a1817e6e715c3c70c49a74c23f09f8b344a891ae5c9258dff3629a7064d7db68d964e20e9afda7b12f7610c421a126506568b41033aa610a0c9b019e2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
